# Generated by Django 5.2.7 on 2025-11-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='estado_garantia',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('NO_APLICA', 'No aplica')], default='VIGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_venc_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='garantia_meses',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='app_inventario.productos')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='app_inventario.sucursales'),
        ),
    ]
