# Generated by Django 5.2.7 on 2025-11-26 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_sucursales_productos_estado_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_qr', to='app_inventario.productos'),
        ),
    ]
