# Generated by Django 5.2.7 on 2025-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_alter_codigoqr_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoqr',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
