# Generated by Django 5.2.7 on 2025-11-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0004_remove_codigoqr_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorias",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="categorias",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="categorias/"),
        ),
    ]
