# Generated by Django 5.2.7 on 2025-11-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0004_remove_codigoqr_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='hora',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='categoria',
            field=models.CharField(blank=True, choices=[('stock', 'Stock'), ('proveedor', 'Proveedor'), ('sistema', 'Sistema'), ('mantenimiento', 'Mantenimiento')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='url_accion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app_inventario.productos'),
        ),
        migrations.AddIndex(
            model_name='notificaciones',
            index=models.Index(fields=['-fecha_creacion'], name='app_inventa_fecha_c_a38a35_idx'),
        ),
        migrations.AddIndex(
            model_name='notificaciones',
            index=models.Index(fields=['usuario', 'leido'], name='app_inventa_usuario_b495bf_idx'),
        ),
    ]
