# Generated by Django 5.2.7 on 2025-11-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0005_alter_notificaciones_options_and_more"),
        ("app_inventario", "0005_remove_categorias_descripcion_categorias_imagen"),
    ]

    operations = []
