# Generated by Django 5.2.7 on 2025-11-27 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0006_merge_20251126_2056"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimientos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("proveedor", models.CharField(blank=True, max_length=200)),
                ("referencia", models.CharField(blank=True, max_length=200)),
                ("comentarios", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.RemoveIndex(
            model_name="notificaciones",
            name="app_inventa_fecha_c_a38a35_idx",
        ),
        migrations.AlterField(
            model_name="notificaciones",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[("mantenimiento", "Mantenimiento"), ("garantia", "Garantía")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="notificaciones",
            index=models.Index(
                fields=["fecha_creacion"], name="app_inventa_fecha_c_0a1165_idx"
            ),
        ),
        migrations.AddField(
            model_name="movimientos",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
